// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6vtnZGrFQmhbGLg4tlVyljI9g_tbMwlM',
    appId: '1:477549801856:web:2f7fab8b7f751329759165',
    messagingSenderId: '477549801856',
    projectId: 'cometa-quality-control-app',
    authDomain: 'cometa-quality-control-app.firebaseapp.com',
    storageBucket: 'cometa-quality-control-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj4INf0Lxiai4PJ3GLJcgbKrxOEtZwOxE',
    appId: '1:477549801856:android:f1d6e6d15ac6912b759165',
    messagingSenderId: '477549801856',
    projectId: 'cometa-quality-control-app',
    storageBucket: 'cometa-quality-control-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_4EvcVeBzh3ktvEJ1vUPmGwKsnPROqHQ',
    appId: '1:477549801856:ios:5899e29885839d88759165',
    messagingSenderId: '477549801856',
    projectId: 'cometa-quality-control-app',
    storageBucket: 'cometa-quality-control-app.appspot.com',
    iosBundleId: 'com.example.qualityControlApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_4EvcVeBzh3ktvEJ1vUPmGwKsnPROqHQ',
    appId: '1:477549801856:ios:5899e29885839d88759165',
    messagingSenderId: '477549801856',
    projectId: 'cometa-quality-control-app',
    storageBucket: 'cometa-quality-control-app.appspot.com',
    iosBundleId: 'com.example.qualityControlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6vtnZGrFQmhbGLg4tlVyljI9g_tbMwlM',
    appId: '1:477549801856:web:90ca7d1afb4be581759165',
    messagingSenderId: '477549801856',
    projectId: 'cometa-quality-control-app',
    authDomain: 'cometa-quality-control-app.firebaseapp.com',
    storageBucket: 'cometa-quality-control-app.appspot.com',
  );
}
